### ISSUE TITLE
Error in fitellipsoidtograins (line 75)

### ISSUE THREAD

**Issue by kpjmcg** [philippesteer/G3Point#1]
Dear Dr Steer,

I am trying to use this tool for my own research but keep incurring the following error when I run the Otira_1cm_grains.ply example provided:

Error using ellipsoid_distance
Too many output arguments.

Error in fitellipsoidtograins (line 75)
        [Ellipsoidm(j).d,Ellipsoidm(j).r2] = ellipsoid_distance(P(:,1),P(:,2),P(:,3),Ellipsoidm(j).p);

Error in G3Point (line 90)
[Ellipsoidm]=fitellipsoidtograins(Pebble,param,nlabels);

Any suggestions on how I fix this? 

It's a very impressive method, thank you for releasing it.

Thanks,
Kieran

**Comment by elmp9** [comment]
dear Dr Steer,

i have the same problem with [kpjmcg](https://github.com/kpjmcg). 
coyld you help me how to fix it ?

thank you

Elena

**Comment by kpjmcg** [comment]
Hi Dr Steer, Elena, 

Returned to this one and it works. The solution is:

- Do not install the quadratic curves package as the ellipsoid_distance function in the current package on matlab **DOES NOT** return r2. 
- Use the package that comes in the zip file which **DOES** return r2.

Maybe a small note in the readme would help? 

Cheers,
Kieran

**Comment by philippesteer** [comment]
Thanks a lot Kieran for that, this is much appreciated! I will put a note asap on the Github main page. Cheers, Philippe
